// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  // TODO: Replace these with your actual Firebase Web configuration
  // Get these values from Firebase Console > Project Settings > Web App

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDizURd-S2nzUmYGNNqr0dhedIAewckEkk',
    appId: '1:554743988495:web:ad5721181a1c5b11d0be7a',
    messagingSenderId: '554743988495',
    projectId: 'nextwave-music-sim',
    authDomain: 'nextwave-music-sim.firebaseapp.com',
    storageBucket: 'nextwave-music-sim.firebasestorage.app',
  );

  // Or run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMz53gdIRDdUJ9JYu7gVRyUEZdGmEPxno',
    appId: '1:554743988495:android:7791fa662d945a94d0be7a',
    messagingSenderId: '554743988495',
    projectId: 'nextwave-music-sim',
    storageBucket: 'nextwave-music-sim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzYo_OSeHy9QxB8GukFv48AsC-4mNuUVE',
    appId: '1:554743988495:ios:9c71e37708fcd20ed0be7a',
    messagingSenderId: '554743988495',
    projectId: 'nextwave-music-sim',
    storageBucket: 'nextwave-music-sim.firebasestorage.app',
    iosBundleId: 'com.example.mobileGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-macos-api-key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'nextwave-demo',
    storageBucket: 'nextwave-demo.appspot.com',
    iosBundleId: 'com.example.mobileGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-windows-api-key',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'nextwave-demo',
    authDomain: 'nextwave-demo.firebaseapp.com',
    storageBucket: 'nextwave-demo.appspot.com',
  );
}